name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y libgsl-dev

      - name: Build
        run: make all

      - name: Run tests
        run: make run-tests

      - name: Run demos
        run: make run-demo run-demo-zalg
